robot:
  _target_: gello.robots.yam.YAMRobot
  channel: can_follow_l
agent:
  _target_: gello.agents.gello_agent.GelloAgent
  port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FTAKRMFX-if00-port0
  dynamixel_config:
    _target_: gello.agents.gello_agent.DynamixelRobotConfig
    joint_ids: [8, 9, 10, 11, 12, 13]
    joint_offsets: [10.99557, 3.14159, 4.71239, 1.5708, 3.14159, 4.71239]
    joint_signs: [1.0, -1.0, -1.0, -1.0, 1.0, 1.0]
    gripper_config: [14, 236.12, 291.884765625]
  start_joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
hz: 60
max_steps: 1000
